"$schema" = "https://starship.rs/config-schema.json"

palette = "noctalia"

format = "[░▒▓](p_main)[  ](bg:p_main fg:on_p_main)[](fg:p_main bg:dir_bg)$directory[](fg:dir_bg bg:git_bg)$git_branch$git_status[](fg:git_bg bg:lang_bg)$nix_shell$nodejs$rust$golang$php[](fg:lang_bg bg:time_bg)$time[ ](fg:time_bg)\n$character"

[character]
error_symbol = "[❯](bold red)"
success_symbol = "[❯](bold green)"

[directory]
format = "[ $path ]($style)"
style = "fg:on_dir bg:dir_bg"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
Documents = "󰈙 "
Downloads = " "
Music = " "
Pictures = " "

[git_branch]
# Mudado de fg:dir_bg para fg:on_git
format = "[[ $symbol $branch ](fg:on_git bg:git_bg)]($style)"
style = "bg:git_bg"
symbol = ""

[git_status]
# Mudado de fg:dir_bg para fg:on_git
format = "[[($all_status$ahead_behind )](fg:on_git bg:git_bg)]($style)"
style = "bg:git_bg"

[golang]
format = "[[ $symbol ($version) ](fg:on_lang bg:lang_bg)]($style)"
style = "bg:lang_bg"
symbol = ""

[nodejs]
format = "[[ $symbol ($version) ](fg:on_lang bg:lang_bg)]($style)"
style = "bg:lang_bg"
symbol = ""

[php]
format = "[[ $symbol ($version) ](fg:on_lang bg:lang_bg)]($style)"
style = "bg:lang_bg"
symbol = ""

[rust]
format = "[[ $symbol ($version) ](fg:on_lang bg:lang_bg)]($style)"
style = "bg:lang_bg"
symbol = ""

[dotnet]
format = "[[ $symbol ($version) ](fg:on_lang bg:lang_bg)]($style)"
style = "bg:lang_bg"
symbol = ""

[lua]
format = "[[ $symbol ($version) ](fg:on_lang bg:lang_bg)]($style)"
style = "bg:lang_bg"
symbol = "󰢱"

[nix_shell]
format = "[[ $symbol ($state) ](fg:on_lang bg:lang_bg)]($style)"
impure_msg = "impure"
pure_msg = "pure"
style = "bg:lang_bg"
symbol = ""

[time]
disabled = false
format = "[[  $time ](fg:on_time bg:time_bg)]($style)"
style = "bg:time_bg"
time_format = "%R"

[palettes.noctalia]
p_main = "green"           # primary
on_p_main = "black"        # on_primary
dir_bg = "yellow"          # secondary
on_dir = "black"           # on_secondary
git_bg = "blue"            # tertiary (para diferenciar do diretório)
on_git = "black"           # on_tertiary
lang_bg = "cyan"           # secondary_fixed_dim
on_lang = "black"          # on_secondary_container
time_bg = "bright-black"   # surface_variant
on_time = "black"          # on_surface_variant
err = "red"                # error
